version: '3.8'

services:
  local_interpreter_server:
    build: 
      context: .
      dockerfile: DockerfileCpu
    image: python310_on_ubuntu2204:1.0
    container_name: container_local_interpreter
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - 8888:8888
    volumes:
      - ./../work:/work
    working_dir: /work
    tty: true